quarkus.application.name=critical-notifier
quarkus.lambda.handler=criticalNotifier
quarkus.log.level=${LOG_LEVEL:INFO}
quarkus.log.console.json=true
quarkus.log.console.json.additional-field."service".value=critical-notifier
