quarkus.application.name=feedback-api
quarkus.http.root-path=/

quarkus.log.level=${LOG_LEVEL:INFO}

feedback.table-name=${FEEDBACK_TABLE_NAME:feedbacks}
feedback.critical-topic-arn=${CRITICAL_TOPIC_ARN:arn:aws:sns:us-east-1:000000000000:critical-feedback}

quarkus.dynamodb.aws.region=${AWS_REGION:us-east-1}
quarkus.sns.aws.region=${AWS_REGION:us-east-1}

%local.quarkus.dynamodb.endpoint-override=${AWS_ENDPOINT_URL:http://localhost:4566}
%local.quarkus.dynamodb.aws.credentials.type=static
%local.quarkus.dynamodb.aws.credentials.static-provider.access-key-id=${AWS_ACCESS_KEY_ID:test}
%local.quarkus.dynamodb.aws.credentials.static-provider.secret-access-key=${AWS_SECRET_ACCESS_KEY:test}

%local.quarkus.sns.endpoint-override=${AWS_ENDPOINT_URL:http://localhost:4566}
%local.quarkus.sns.aws.credentials.type=static
%local.quarkus.sns.aws.credentials.static-provider.access-key-id=${AWS_ACCESS_KEY_ID:test}
%local.quarkus.sns.aws.credentials.static-provider.secret-access-key=${AWS_SECRET_ACCESS_KEY:test}

%test.feedback.table-name=feedbacks
%test.feedback.critical-topic-arn=arn:aws:sns:us-east-1:000000000000:critical-feedback