services:
  fakecloud:
    image: ghcr.io/faiscadev/fakecloud:latest
    container_name: aws-fakecloud
    network_mode: host
    environment:
      - SERVICES=dynamodb,sns,ses,events,lambda,logs,cloudwatch,iam,apigateway
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - FAKECLOUD_EXTERNAL_URL=http://localhost:4566
      - FAKECLOUD_IN_CONTAINER=0
      - FAKECLOUD_STORAGE_MODE=persistent
      - FAKECLOUD_DATA_PATH=${PWD}/.fakecloud
      - DEBUG=1
    volumes:
      - "${PWD}/.fakecloud:${PWD}/.fakecloud"
      - "/var/run/docker.sock:/var/run/docker.sock"
