quarkus.application.name=weekly-report
quarkus.lambda.handler=weeklyReport
quarkus.log.level=${LOG_LEVEL:INFO}
quarkus.log.console.json=true
quarkus.log.console.json.additional-field."service".value=weekly-report
